name: Aone APK Generator
on:
  release:
    types: [published]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get Bundletool
        run: wget https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar -O bundletool.jar

      - name: Download AAB from Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: '.*\.aab' # Mencari file apapun yang berakhiran .aab
          regex: true
          target: './app.aab' # Disimpan dengan nama sementara app.aab agar script di bawah lancar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert AAB to APK
        run: |
          # Menggunakan --mode=universal agar bisa diinstall di semua HP
          java -jar bundletool.jar build-apks --bundle=app.aab --output=app.apks --mode=universal
          unzip app.apks -d hasil_apk
          mv hasil_apk/universal.apk Aone-Attendance-Siswa.apk

      - name: Upload APK back to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Aone-Attendance-Siswa.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
