name: Aone Auto APK
on:
  release:
    types: [published]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Bundletool
        run: wget https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar -O bundletool.jar

      - name: Ambil AAB dari Release
        run: |
          # Perintah ini memaksa ambil file .aab dari release yang baru saja dipublish
          GH_ASSET_URL=$(curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
            | jq -r '.assets[] | select(.name | endswith(".aab")) | .url')
          
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/octet-stream" \
            -o "app.aab" "$GH_ASSET_URL"

      - name: Convert
        run: |
          java -jar bundletool.jar build-apks --bundle=app.aab --output=app.apks --mode=universal
          unzip app.apks -d hasil
          mv hasil/universal.apk Aone-Attendance-Siswa.apk

      - name: Upload APK ke Release
        uses: softprops/action-gh-release@v2
        with:
          files: Aone-Attendance-Siswa.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
